### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by ssbrewster** [Proj4J/proj4j#3]
I've used proj4js in the past but now I need the Java equivalent. Is this project still being maintained, and would you recommend it's use in production?

**Comment by willtemperley** [comment]
That seems to be a complicated question.  

So having looked into this a little, it appears GeoTrellis amalgamated it into their project:

https://github.com/locationtech/geotrellis/tree/master/proj4/src/main/java/org/osgeo/proj4j

But they've decided a separate version would be better:
https://www.locationtech.org/proposals/proj4j

Which would be this one which uses SBT (!):
https://github.com/dwins/proj4j

but active development seems to be going on only on the geotrellis version.

Hmmm.

**Comment by sebasbaumh** [comment]
I tried to set up a [fork](https://github.com/sebasbaumh/proj4j/tree/sb) without SBT and with a thread safe [`BasicCoordinateTransformation`](https://github.com/sebasbaumh/proj4j/commit/55a24aac8443859cefeae36e1e67363cb6ce9588).

Currently it looks to me like the only change in [their repository](https://github.com/locationtech/geotrellis/tree/master/proj4/src/main/java/org/osgeo/proj4j) is replacing the original copyright disclaimer with their own.

Like [here](https://github.com/locationtech/geotrellis/blob/master/proj4/src/main/java/org/osgeo/proj4j/ProjectionException.java#L2):
````
Copyright 2006 Jerry Huxtable
````
vs. [here](https://github.com/dwins/proj4j/blob/master/src/main/java/org/osgeo/proj4j/ProjectionException.java#L2):
````
Copyright 2016 Martin Davis, Azavea
````

Together with mixing in Scala for tests that looks rather scary to me ;-)
